language: rust
sudo: required

after_success:
  - curl https://stainless-steel.github.io/travis/after_success.sh | bash

env:
  global:
    secure: q11MTzwAQ0k1boPtqqjmDSPoYo+o5l7JwZO5jQz4LYnw6Gc3fDpju+bzIW8lk2MbZjRrTaTuFWPi0O6TtScX5jkJIEZe9to1fQ5uFZNOvzSKep4S6KtneAHdSZCkDTBk9Y0TA19cUdlgOzaIaw6Dwte1kCYU3Qa+CoUy6W4Y1Bo=

notifications:
  email: false
