[package]
name = "probability"
version = "0.3.1"
authors = [
  "Ivan Ukhov <ivan.ukhov@gmail.com>",
  "Jon Lund Steffensen <jonlst@gmail.com>",
  "Rúnar Berg Baugsson Sigríðarson <runarberg@zoho.com>",
]
license = "MIT"
repository = "https://github.com/stainless-steel/probability"
homepage = "https://github.com/stainless-steel/probability"
documentation = "https://stainless-steel.github.io/probability"
description = "The package provides a probability-theory toolbox."

[dependencies]
num = "*"
rand = "*"
special = "*"

[dev-dependencies]
assert = "*"
