[package]
name = "probability"
version = "0.3.0"
authors = ["Ivan Ukhov <ivan.ukhov@gmail.com>"]
license = "MIT"
repository = "https://github.com/stainless-steel/probability"
homepage = "https://github.com/stainless-steel/probability"
documentation = "https://stainless-steel.github.io/probability"
description = "The package provides a probability-theory toolbox."

[dependencies]
num = "*"
rand = "*"
special = "*"

[dev-dependencies]
assert = "*"
