[package]
name = "probability"
version = "0.1.0"
authors = ["Ivan Ukhov <ivan.ukhov@gmail.com>"]
license = "MIT"
repository = "https://github.com/stainless-steel/probability"
homepage = "https://github.com/stainless-steel/probability"
documentation = "https://stainless-steel.github.io/probability"
description = "The library provides a probability-theory toolbox."

[dependencies]
special = "0.1"

[dev-dependencies]
assert = "0.1"
